//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraSolucion.UI.BusinessLogicWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MiPrimeraSolucion.BL")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessLogicWcf.IPruebaBL")]
    public interface IPruebaBL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/SayHello", ReplyAction="http://tempuri.org/IPruebaBL/SayHelloResponse")]
        string SayHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/SayHello", ReplyAction="http://tempuri.org/IPruebaBL/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/SayHelloToSomeone", ReplyAction="http://tempuri.org/IPruebaBL/SayHelloToSomeoneResponse")]
        string SayHelloToSomeone(string someone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/SayHelloToSomeone", ReplyAction="http://tempuri.org/IPruebaBL/SayHelloToSomeoneResponse")]
        System.Threading.Tasks.Task<string> SayHelloToSomeoneAsync(string someone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/SayMessageToSomeone", ReplyAction="http://tempuri.org/IPruebaBL/SayMessageToSomeoneResponse")]
        string SayMessageToSomeone(string someone, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/SayMessageToSomeone", ReplyAction="http://tempuri.org/IPruebaBL/SayMessageToSomeoneResponse")]
        System.Threading.Tasks.Task<string> SayMessageToSomeoneAsync(string someone, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/GetData", ReplyAction="http://tempuri.org/IPruebaBL/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/GetData", ReplyAction="http://tempuri.org/IPruebaBL/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPruebaBL/GetDataUsingDataContractResponse")]
        MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType GetDataUsingDataContract(MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPruebaBL/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPruebaBL/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType> GetDataUsingDataContractAsync(MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPruebaBLChannel : MiPrimeraSolucion.UI.BusinessLogicWcf.IPruebaBL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PruebaBLClient : System.ServiceModel.ClientBase<MiPrimeraSolucion.UI.BusinessLogicWcf.IPruebaBL>, MiPrimeraSolucion.UI.BusinessLogicWcf.IPruebaBL {
        
        public PruebaBLClient() {
        }
        
        public PruebaBLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PruebaBLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PruebaBLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PruebaBLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello() {
            return base.Channel.SayHello();
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync() {
            return base.Channel.SayHelloAsync();
        }
        
        public string SayHelloToSomeone(string someone) {
            return base.Channel.SayHelloToSomeone(someone);
        }
        
        public System.Threading.Tasks.Task<string> SayHelloToSomeoneAsync(string someone) {
            return base.Channel.SayHelloToSomeoneAsync(someone);
        }
        
        public string SayMessageToSomeone(string someone, string message) {
            return base.Channel.SayMessageToSomeone(someone, message);
        }
        
        public System.Threading.Tasks.Task<string> SayMessageToSomeoneAsync(string someone, string message) {
            return base.Channel.SayMessageToSomeoneAsync(someone, message);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType GetDataUsingDataContract(MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType> GetDataUsingDataContractAsync(MiPrimeraSolucion.UI.BusinessLogicWcf.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
